# Created with WinGet Releaser using komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Exelearning.Exelearning
PackageVersion: 3.0.0-rc3
PackageLocale: en-US
Publisher: INTEF
PublisherUrl: https://exelearning.net/
PublisherSupportUrl: https://github.com/exelearning/exelearning/issues
Author: exelearning
PackageName: eXeLearning
PackageUrl: https://exelearning.net/
License: AGPL-3.0
LicenseUrl: https://github.com/exelearning/exelearning/blob/HEAD/LICENSE
Copyright: Copyright © 2025 INTEF
ShortDescription: eXeLearning is a free authoring tool to create educational resources.
Description: eXeLearning is an open source authoring tool to create educational resources in multiple formats (Web, SCORM, ePub, etc.). It allows teachers and institutions to design, develop and publish digital content without requiring HTML or XML knowledge.
Moniker: exelearning
Tags:
- educational
- exelearning
ReleaseNotes: |-
  Added
  - New default file extension: elp → elpx
  - Notarization of the macOS version
  - New screenshots of styles
  - Information about styles (detailed descriptions and recognitions)
  Fixed
  - Rubric iDevice median score calculation
  - JavaScript errors when more than one UDL iDevice is present on a page
  - Accessibility issues in the Favorite iDevices panel
ReleaseNotesUrl: https://github.com/exelearning/exelearning/releases/tag/v3.0.0-rc3
ManifestType: defaultLocale
ManifestVersion: 1.10.0
