# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 12.4.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Commands:
- floorp
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- url
- webp
- xht
- xhtml
ReleaseDate: 2025-10-27
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v12.4.0/floorp-windows-x86_64.installer.exe
  InstallerSha256: 228AD629D64513BFADABDA629C1C83F8167149F700D8BF013D539E40E5F47706
  AppsAndFeaturesEntries:
  - DisplayName: Ablaze Floorp (x64 en-US)
    ProductCode: Ablaze Floorp 12.4.0 (x64 en-US)
ManifestType: installer
ManifestVersion: 1.10.0
